# Generated by Django 2.1.5 on 2019-01-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_stuff'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stf',
            field=models.ForeignKey(default=None, on_delete='cascade', to='dashboard.Stuff'),
            preserve_default=False,
        ),
    ]
