# Generated by Django 2.1.5 on 2019-01-07 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_person_stf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='cat',
        ),
    ]
