# Generated by Django 2.1.5 on 2019-01-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_person_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stf',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Stuff',
        ),
    ]
