# Generated by Django 2.1.5 on 2019-01-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190114_1701'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='manager',
            field=models.CharField(choices=[('Jean Pierre-Louis', 'JP'), ('jack', 'Jack'), ('jason', 'Jason')], default='JP', max_length=120),
        ),
    ]
