# Generated by Django 2.1.5 on 2019-01-14 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_taskmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password',
            field=models.CharField(default='password1', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='creator_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserModel'),
        ),
    ]
