# Generated by Django 2.1.5 on 2019-01-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20190114_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UserModel'),
        ),
        migrations.AlterField(
            model_name='taskmodel',
            name='creator_name',
            field=models.CharField(max_length=30),
        ),
    ]
