# Generated by Django 2.1.5 on 2019-01-14 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190114_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=30)),
                ('feedback', models.CharField(max_length=220)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('assigned_to', models.ManyToManyField(to='dashboard.UserModel')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
