# Generated by Django 2.1.5 on 2019-01-14 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_feedbackmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feedbackmodel',
            options={'verbose_name': 'Feedback'},
        ),
    ]
