# Generated by Django 2.1.5 on 2019-01-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_usermodel_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='photo',
            field=models.ImageField(default='../oneOnOne/static/images/android-desktop.png', upload_to='images/'),
        ),
    ]
